"""add image in hotel teable

Revision ID: 8b5ca86f8fc2
Revises: 574d09057938
Create Date: 2024-07-17 15:22:38.174992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5ca86f8fc2'
down_revision = '574d09057938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
